services:
  vault:
    container_name: vault
    image: "vaultwarden/server:1.35.2-alpine"
    volumes:
      - ./vault:/data
    restart: always
  caddy:
    container_name: caddy
    image: caddy:2.11-alpine
    ports:
      - 443:443
    depends_on:
      - vault
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - /var/run/tailscale/tailscaled.sock:/var/run/tailscale/tailscaled.sock
    restart: always
