services:
  vault:
    image: "vaultwarden/server:1.32.1-alpine"
    restart: always
    volumes:
      - ./vault:/data

  proxy:
    build:
      context: ./proxy
    restart: always
    env_file:
      - .env
    depends_on:
      - vault
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./tailscale:/var/lib/tailscale
